#!/usr/bin/env bash
# This script is based off of Vensci's XMonad workspace script.
# Basically all credit goes to him. I just made a few personal adjustments in order
# to get it working more consistently.

# This function is responsible for receiving data from wmctrl and updating the icons
# and class names so that they match the actual current state of the window manager.
nameWs() {
  buffered=""
  wmctrl -d | awk '{print $1 " " "\\"$2 " " $9}' | while read -r id active name; do
    name="${name#*_}"
    active=${active##*\\} && active=${active%% *}

    if wmctrl -l | grep --regexp '.*\s\+'"$id"'\s\+.*' >/dev/null; then
      wClass="occupied"
    else
      wClass="inactive"
    fi

    if [ "$active" == '*' ]; then
      wClass="active"
    fi

    buffered+="(button :class \"$wClass\" :tooltip \"Switch to $name?\" :onclick \"wmctrl -s $id\" \"$name\")"
    echo -n "$buffered"
    buffered=""
  done
}

# This are the eww box attributes that will be used in the workspace widget.
box_attrs=':orientation "h" :class "ws" :space-evenly false :spacing 12 :valign 0.5'

# This checks the root window for updates, updating the nameWs output every 
# time a change occurs to a workspace (window opened or focused desktop).
xprop -spy -root | while read -r _; do
echo "(box $box_attrs $(nameWs))"
done
